# Generated by Django 4.2.1 on 2023-07-18 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0004_alter_news_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='photo',
            new_name='link_photo',
        ),
    ]
