# Generated by Django 4.2.1 on 2023-07-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('berita', '0005_rename_photo_news_link_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='link_photo',
            new_name='photo_link',
        ),
    ]
